--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/15/2018 8:11:52 PM
-- Server version: 5.7.20-log
-- Client version: 4.1
--


SET NAMES 'utf8';
